routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});


Auth::routes();

Route::get('/home', 'HomeController@index');

Route::resource('homes', 'homeController');

Route::resource('contacts', 'contactController');

Route::post('/send', 'EmailController@send');

Route::get('/getBranchOffice', 'branch_officeController@getBranchOffice');
Route::resource('branchOffices', 'branch_officeController');

app/Models/branch_office.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class branch_office
 * @package App\Models
 * @version October 18, 2018, 10:07 pm UTC
 *
 * @property string name
 * @property string address
 * @property float lat
 * @property float lng
 * @property string description
 */
class branch_office extends Model
{

    public $timestamps = false;

    public $table = 'branch_office';

    protected $primaryKey = 'id';

    public $fillable = [
        'name',
        'address',
        'lat',
        'lng',
        'description'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'name' => 'string',
        'address' => 'string',
        'lat' => 'float',
        'lng' => 'float',
        'description' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    
}

app/Http/Controllers/branch_officeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Createbranch_officeRequest;
use App\Http\Requests\Updatebranch_officeRequest;
use App\Repositories\branch_officeRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;
use App\Models\Branch_office;

class branch_officeController extends AppBaseController
{
    /** @var  branch_officeRepository */
    private $branchOfficeRepository;

    public function __construct(branch_officeRepository $branchOfficeRepo)
    {
        $this->branchOfficeRepository = $branchOfficeRepo;
    }

    /*
     * get brachoffices
     */
    public function getBranchOffice(){

        $branchOffice = Branch_office::all();

        return response()->json([
            'success' => 1,
            'data' => $branchOffice]);
    }

    /**
     * Display a listing of the branch_office.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->branchOfficeRepository->pushCriteria(new RequestCriteria($request));
        $branchOffices = $this->branchOfficeRepository->all();

        return view('branch_offices.index')
            ->with('branchOffices', $branchOffices);
    }

    /**
     * Show the form for creating a new branch_office.
     *
     * @return Response
     */
    public function create()
    {
        return view('branch_offices.create');
    }

    /**
     * Store a newly created branch_office in storage.
     *
     * @param Createbranch_officeRequest $request
     *
     * @return Response
     */
    public function store(Createbranch_officeRequest $request)
    {
        $input = $request->all();

        $branchOffice = $this->branchOfficeRepository->create($input);

        Flash::success('Branch Office saved successfully.');

        return redirect(route('branchOffices.index'));
    }

    /**
     * Display the specified branch_office.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $branchOffice = $this->branchOfficeRepository->findWithoutFail($id);

        if (empty($branchOffice)) {
            Flash::error('Branch Office not found');

            return redirect(route('branchOffices.index'));
        }

        return view('branch_offices.show')->with('branchOffice', $branchOffice);
    }

    /**
     * Show the form for editing the specified branch_office.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $branchOffice = $this->branchOfficeRepository->findWithoutFail($id);

        if (empty($branchOffice)) {
            Flash::error('Branch Office not found');

            return redirect(route('branchOffices.index'));
        }

        return view('branch_offices.edit')->with('branchOffice', $branchOffice);
    }

    /**
     * Update the specified branch_office in storage.
     *
     * @param  int              $id
     * @param Updatebranch_officeRequest $request
     *
     * @return Response
     */
    public function update($id, Updatebranch_officeRequest $request)
    {
        $branchOffice = $this->branchOfficeRepository->findWithoutFail($id);

        if (empty($branchOffice)) {
            Flash::error('Branch Office not found');

            return redirect(route('branchOffices.index'));
        }

        $branchOffice = $this->branchOfficeRepository->update($request->all(), $id);

        Flash::success('Branch Office updated successfully.');

        return redirect(route('branchOffices.index'));
    }

    /**
     * Remove the specified branch_office from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $branchOffice = $this->branchOfficeRepository->findWithoutFail($id);

        if (empty($branchOffice)) {
            Flash::error('Branch Office not found');

            return redirect(route('branchOffices.index'));
        }

        $this->branchOfficeRepository->delete($id);

        Flash::success('Branch Office deleted successfully.');

        return redirect(route('branchOffices.index'));
    }
}

resources/views/branch_offices/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Branch Office
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'branchOffices.store']) !!}

                        @include('branch_offices.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/branch_offices/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Address Field -->
<div class="form-group col-sm-6">
    {!! Form::label('address', 'Address:') !!}
    {!! Form::text('address', null, ['class' => 'form-control']) !!}
</div>

<!-- Lat Field -->
<div class="form-group col-sm-6">
    {!! Form::label('lat', 'Lat:') !!}
    {!! Form::number('lat', null, ['class' => 'form-control']) !!}
</div>

<!-- Lng Field -->
<div class="form-group col-sm-6">
    {!! Form::label('lng', 'Lng:') !!}
    {!! Form::number('lng', null, ['class' => 'form-control']) !!}
</div>

<!-- Description Field -->
<div class="form-group col-sm-6">
    {!! Form::label('description', 'Description:') !!}
    {!! Form::text('description', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('branchOffices.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/branch_offices/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Branch Offices</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('branchOffices.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('branch_offices.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/branch_offices/modalBranchOffice.blade.php
{!! Form::open(['id' => 'formBranchOffice', 'name' => 'formValidateBranchOffice', 'data-parsley-validate' => 'true','data-action'=>'']) !!}
{!! Form::hidden('_method', null, ['data-id' => '1']) !!}
<div class="modal fade in" id="modal_home" role="dialog" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true" id="close_modal_branch_office"><i class="fa fa-times"></i></button>
                <h4 class="modal-title">Configuracion de Inicio</h4>
            </div>
            <div class="modal-body loading-modal-home">
                <div class="row validate-home">
                    @include('homes.fields')
                </div>
            </div>
        </div>
    </div>
</div>
{!! Form::close() !!}

resources/views/branch_offices/table.blade.php
<table class="table table-responsive" id="branchOffices-table">
    <thead>
        <tr>
            <th>Name</th>
        <th>Address</th>
        <th>Lat</th>
        <th>Lng</th>
        <th>Description</th>
            <th colspan="3">Action</th>
        </tr>
    </thead>
    <tbody>
    @foreach($branchOffices as $branchOffice)
        <tr>
            <td>{!! $branchOffice->name !!}</td>
            <td>{!! $branchOffice->address !!}</td>
            <td>{!! $branchOffice->lat !!}</td>
            <td>{!! $branchOffice->lng !!}</td>
            <td>{!! $branchOffice->description !!}</td>
            <td>
                {!! Form::open(['route' => ['branchOffices.destroy', $branchOffice->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('branchOffices.show', [$branchOffice->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('branchOffices.edit', [$branchOffice->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>